server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}  # ??? ??? ???? ???? ? ?
            client-secret: ${KAKAO_CLIENT_SECRET}  # ??? ??? ???? ???? ? ???
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  datasource:
    url: jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ?? ??? update / ????? none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      accept-empty-string-as-null-object: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: roundandgo.official@gmail.com
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  cache:
    type: simple

jwt:
  secret-key:  ${JWT_SECRET_KEY}  # JWT ???

logging:
  level:
    org.springframework.web: DEBUG   # ? ??: Spring Web MVC ?? ?? ??
    org.springframework.security: DEBUG    # ? ??: Security ?? ?? ?? ??

management:
  endpoints:
    web:
      exposure:
        include: '*' # ? ??: ?? ????? ??

culture-api:
  key: ${CULTURE_API_KEY}

# OpenAI API 설정
openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1
    model: gpt-4o-mini
    max-tokens: 1000
    temperature: 0.7
