name: Notion 연동 - 이슈 생성 시

on:
  issues:
    types: [opened]

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest

    steps:
      - name: 상태 값 라벨로 설정
        id: set_status
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')
          STATUS="시작 전"
          for label in $LABELS; do
            if [[ "$label" == *"doing"* ]]; then
              STATUS="진행 중"
            elif [[ "$label" == *"done"* ]]; then
              STATUS="완료"
            fi
          done
          echo "선택된 상태: $STATUS"
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Notion에 이슈 내용 전송
        run: |
          curl -X POST 'https://api.notion.com/v1/pages' \
            -H "Authorization: Bearer ${{ secrets.NOTION_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data @- <<EOF
{
  "parent": { "database_id": "${{ secrets.NOTION_DATABASE_ID }}" },
  "properties": {
    "할 일": {
      "title": [
        { "text": { "content": "${{ github.event.issue.title }}" } }
      ]
    },
    "설명": {
      "rich_text": [
        { "text": { "content": "${{ github.event.issue.body }}" } }
      ]
    },
    "상태": {
      "select": {
        "name": "${{ steps.set_status.outputs.status }}"
      }
    },
    "담당자": {
      "multi_select": [
        { "name": "이여재" }
      ]
    }
  }
}
EOF
