name: Notion 연동 - 이슈 생성 시

on:
  issues:
    types: [opened]

jobs:
  sync-to-notion:
    runs-on: ubuntu-latest

    steps:
      - name: 상태 값 라벨로 설정
        id: set_status
        run: |
          LABELS=$(echo '${{ toJson(github.event.issue.labels) }}' | jq -r '.[].name')
          STATUS="시작 전"
          for label in $LABELS; do
            if [[ "$label" == *"doing"* ]]; then
              STATUS="진행 중"
            elif [[ "$label" == *"done"* ]]; then
              STATUS="완료"
            fi
          done
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: Notion에 이슈 내용 전송
        shell: bash
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          STATUS: ${{ steps.set_status.outputs.status }}
        run: |
          SAFE_BODY=$(jq -Rn --arg str "$ISSUE_BODY" '$str')

          echo "{" > request.json
          echo "  \"parent\": { \"database_id\": \"${NOTION_DATABASE_ID}\" }," >> request.json
          echo "  \"properties\": {" >> request.json
          echo "    \"할 일\": {" >> request.json
          echo "      \"title\": [" >> request.json
          echo "        { \"text\": { \"content\": \"${ISSUE_TITLE}\" } }" >> request.json
          echo "      ]" >> request.json
          echo "    }," >> request.json
          echo "    \"설명\": {" >> request.json
          echo "      \"rich_text\": [" >> request.json
          echo "        { \"text\": { \"content\": ${SAFE_BODY} } }" >> request.json
          echo "      ]" >> request.json
          echo "    }," >> request.json
          echo "    \"상태\": {" >> request.json
          echo "      \"select\": { \"name\": \"${STATUS}\" }" >> request.json
          echo "    }," >> request.json
          echo "    \"담당자\": {" >> request.json
          echo "      \"multi_select\": [" >> request.json
          echo "        { \"name\": \"이여재\" }" >> request.json
          echo "      ]" >> request.json
          echo "    }" >> request.json
          echo "  }" >> request.json
          echo "}" >> request.json

          curl -X POST 'https://api.notion.com/v1/pages' \
            -H "Authorization: Bearer ${NOTION_TOKEN}" \
            -H "Content-Type: application/json" \
            -H "Notion-Version: 2022-06-28" \
            --data "@request.json"
